"""Rule-based intent classification for meeting transcripts."""

from __future__ import annotations


INTENT_KEYWORDS = {
    "churn_risk": {
        "cancelar",
        "cancele",
        "cancelamento",
        "encerrar",
        "trocar de fornecedor",
        "desistir",
        "sair",
        "não vou continuar",
        "nao vou continuar",

        "quero cancelar",
        "vou cancelar",
        "pode cancelar",
        "cancela isso",
        "cancelei",
        "cancelando",

        "encerramento",
        "encerrar contrato",
        "finalizar contrato",
        "rescindir",
        "rescisão",
        "terminar contrato",
        "parar de usar",
        "vou parar",
        "parei de usar",

        "não continuo",
        "nao continuo",
        "não quero continuar",
        "nao quero continuar",
        "vou sair",
        "quero sair",
        "saindo fora",
        "tô fora",
        "to fora",
        "tô vazando",
        "to vazando",
        "caindo fora",

        "vou trocar",
        "mudar de empresa",
        "fechar com outro",
        "já contratei outro",
        "ja contratei outro",
        "estou com outro",
        "vou pra outro",

        "desisti",
        "quero desistir",
        "não quero mais",
        "nao quero mais",
        "cansei disso",
        "já deu",
        "ja deu",
        "não rola mais",
        "nao rola mais",
        "não vale a pena",
        "nao vale a pena",

        "não funcionou",
        "nao funcionou",
        "não deu certo",
        "nao deu certo",
        "só tive problema",
        "so tive problema",
        "muita dor de cabeça",
        "dor de cabeca",
        "péssima experiência",
        "pessima experiencia",
        "horrível",
        "horrivel",
        "não presta",
        "nao presta",
        "mó ruim",
        "mo ruim",
        "ruim demais",
    },

    "price_objection": {
        "caro",
        "preço",
        "preco",
        "valor alto",
        "muito caro",
        "desconto",
        "orçamento",
        "orcamento",
        "fora do orçamento",

        "caríssimo",
        "caro demais",
        "preço alto",
        "preco alto",
        "valor elevado",
        "custa caro",
        "salgado",
        "preço salgado",
        "preco salgado",

        "fora do budget",
        "sem orçamento",
        "não cabe no orçamento",
        "nao cabe no orçamento",
        "estourou o orçamento",
        "sem verba",
        "sem grana",
        "sem dinheiro",
        "tá apertado",
        "ta apertado",

        "mais barato",
        "tem mais barato",
        "concorrente mais barato",
        "outro mais barato",
        "achei mais em conta",
        "mais em conta",

        "tem desconto",
        "consegue desconto",
        "melhorar preço",
        "melhorar o valor",
        "negociar preço",
        "fechar por menos",
        "abaixar preço",
        "reduzir valor",

        "não vale o preço",
        "nao vale o preco",
        "não compensa",
        "nao compensa",
        "custo benefício ruim",
        "custo beneficio ruim",
        "muito caro pro que entrega",

        "caro pra caramba",
        "caro pra cacete",
        "caro demais da conta",
        "preço puxado",
        "preco puxado",
        "tá caro demais",
        "ta caro demais",
        "não cabe no bolso",
        "nao cabe no bolso",
    },

    "upsell_opportunity": {
        "upgrade",
        "mais usuários",
        "mais usuarios",
        "novo módulo",
        "novo modulo",
        "ampliar",
        "expandir",
        "contratar mais",
        "mais licenças",
        "mais licencas",

        "quero expandir",
        "aumentar uso",
        "escalar",
        "crescer",
        "crescer com",

        "adicionar usuários",
        "adicionar usuarios",
        "comprar mais licenças",
        "incluir mais gente",
        "aumentar equipe",
        "colocar mais pessoas",

        "fazer upgrade",
        "subir plano",
        "mudar de plano",
        "plano maior",
        "plano mais completo",
        "plano acima",

        "contratar módulo",
        "adicionar funcionalidade",
        "preciso de mais recursos",
        "tem essa feature",
        "tem essa funcionalidade",
        "preciso disso também",

        "quero contratar mais",
        "vamos contratar mais",
        "quero incluir",
        "tem como adicionar",
        "como fazer upgrade",

        "bora expandir",
        "vamos crescer",
        "quero botar mais gente",
        "quero turbinar",
    },

    "satisfaction": {
        "gostei",
        "ótimo",
        "otimo",
        "excelente",
        "satisfeito",
        "satisfeita",
        "funcionando bem",
        "deu certo",
        "muito bom",

        "gostamos",
        "perfeito",
        "top",
        "show",
        "bom demais",
        "sensacional",
        "maravilhoso",

        "bem satisfeito",
        "bem satisfeita",
        "estamos satisfeitos",
        "tudo certo",
        "tudo ok",
        "tudo tranquilo",

        "funciona bem",
        "rodando bem",
        "tá funcionando",
        "ta funcionando",
        "está dando certo",
        "ta dando certo",
        "redondinho",

        "teve resultado",
        "bons resultados",
        "resultado positivo",
        "valeu a pena",
        "compensou",

        "atendimento ótimo",
        "atendimento otimo",
        "suporte excelente",
        "gostei do suporte",
        "equipe muito boa",
        "atendimento rápido",

        "bom pra caramba",
        "bom pra cacete",
        "top demais",
        "show de bola",
        "massa",
        "arretado",
        "da hora",
        "maneiro",
        "bacana",
        "legal demais",
    },
}


def classify_intent(text: str) -> str:
    """Classify text intent using simple keyword rules."""
    normalized_text = (text or "").strip().lower()
    if not normalized_text:
        return "neutral"

    for intent, keywords in INTENT_KEYWORDS.items():
        if any(keyword in normalized_text for keyword in keywords):
            return intent

    return "neutral"
